### 1. Write a Python Program to Add Two Matrices

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,7,8],[5,6,4],[3,2,1]])

In [9]:

def add_mat(matric1, matric2):
    if matric1.shape == matric2.shape:
        return matric1+matric2
        
print(add_mat(a,b))      

[[10  9 11]
 [ 9 11 10]
 [10 10 10]]


### 2. Write a Python Program to Multiply Two Matrices?

In [20]:
def multi_mat(m1,m2):
    result = np.empty((len(m1[0]), len(m2)))

    for i in range(len(m2)):
        for j in range(len(m1[0])):
            for k in range(len(m1)):
                result[i][j] += m2[i][k] * m1[k][j]

    for r in result:
        print(r)

multi_mat(a,b)

[ 93. 117. 141.]
[57. 72. 87.]
[18. 24. 30.]


### 3. Write a Python Program to Transpose a Matrix?

In [23]:
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [34]:
array = "I am Nikunj Ramani"
def sort1(array):
    a = array.split(" ")
    for i in range(len(a)):
        a[i] = a[i].lower()
        a.sort()
    return ''.join(a)

print(sort1(array))

Nikunjamiramani


### 5. Write a Python Program to Remove Punctuation From a String?

In [37]:
a = "jnvj#$% knjnjg%^& @#$"

def punct(a):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for i in a.lower():
        if i in punctuations:
            a = a.replace(i, "")
    print(a)
    
punct(a)

jnvj knjnjg 
